### ISSUE TITLE
ResourceNotFound: multi_robot_system

### ISSUE THREAD

**Issue by bluetulip89** [tanukitoshika/multi_robot_sim#1]
While executing multi_robot_sim robots_gazebo_rviz.launch,  I am getting the below error due to missing of multi_robot_system pkg. Can you please share it or add in the repo? Thanks in advance

raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: multi_robot_system
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/bluetronics/Documents/mod_ws/src
ROS path [2]=/home/bluetronics/new_ws/src
ROS path [3]=/home/bluetronics/sam_ws/src
ROS path [4]=/home/bluetronics/catkin_ws/src
ROS path [5]=/home/bluetronics/wss/src
ROS path [6]=/opt/ros/kinetic/share

**Comment by bluetulip89** [comment]
Solved by renaming package name. Closing the issue.

**Comment by willchamberlain** [comment]
That update is in  in  /launch/include/robot.launch.xml
